### ISSUE TITLE
depmod fallouts from module-directory

### ISSUE THREAD

**Issue by evelikov** [kmod-project/kmod#85] opened 2024-08-22 13:05 UTC
[Initially reported](https://lore.kernel.org/all/CAK7LNARYK-xjBS8puEM9xFtmjBNW6KJ2Qd6f7diZkdEEbUgVHA@mail.gmail.com/) by Masahiro Yamada on the ML, although it seemingly got lost in the noise.

Tl:Dr: People currently use their native kmod when cross-building kernels. So if you use `/usr/lib/modules` for your kmod, while the target platform uses `/lib/modules`, depmod fails.

One option is to require cross-compile (aware) kmod and another to add a new argument to depmod (basedir is not sufficient) Former is more idealistic, although not too practical since a few people have hit this and more to follow.

@hramrach what's your take? Can you lend a hand to fix this bug/regression?

**Comment by lucasdemarchi** [comment] 2024-08-22 13:18
See my reply: https://lore.kernel.org/all/5gx6vt4tzgk4zvboxrrahexr4ja6zm6fisjshdvnlfihsysqzb@quhp42ydtvh2/

I think we need the -m|--module-dir to be future proof. Kernel should default it to the output of `pkg-config --variable=module_directory kmod`.  For compatibility and the common case (host on /lib/modules, target on /usr/lib/modules) it's possible to do without that by hacking the path passed to depmod (e.g. append the /usr in $INSTALL_MOD_PATH), but more complex cases in which target or host are in random dirs, I don't think so.

**Comment by rfc1036** [comment] 2024-08-26 17:07
I do not think that Debian needs to care about cross-compiling to targets which do not implement merged-/usr, since it is a more and more unsupported configuration, but please let me know if I am missing anything.

**Comment by lucasdemarchi** [comment] 2024-08-26 17:54
@rfc1036 the problem is actually cross-compiling to a target with a different --with-module-directory, or when mixing new (on a host with --with-module-directory=<something>) and old (on the target, that is hardcoding /lib/modules before that became configurable)

**Comment by hramrach** [comment] 2024-08-26 18:03
Since  the kernel support for --with-module-directory= was not merged merely compiling a kernel when you used --with-module-directory= triggers a problem. However, multiple patches to implement that in the kernel were rejected, and it's not clear what is acceptable for Masahiro Yamada to merge.

Of course, you can apply one of the historical versions of the patch locally.

**Comment by rfc1036** [comment] 2024-08-26 20:51
But how can this relevant **if** `/lib/modules/` and `/usr/lib/modules/` are the same directory, thanks to a symlink?

**Comment by lucasdemarchi** [comment] 2024-08-27 05:29
@rfc1036 See scripts/depmod.sh in the kernel:

```
if test -n "$INSTALL_MOD_PATH"; then
        set -- "$@" -b "$INSTALL_MOD_PATH"
fi
exec "$DEPMOD" "$@" "$KERNELRELEASE"
```

And the module installation:
Makefile:MODLIB = $(INSTALL_MOD_PATH)/lib/modules/$(KERNELRELEASE)

Also the pkg building rules use INSTALL_MOD_PATH so the modules are copied to a stash dir before they are packaged:
```
scripts/package/PKGBUILD:       ${MAKE} INSTALL_MOD_PATH="${pkgdir}/usr" INSTALL_MOD_STRIP=1 \ 
scripts/package/builddeb:       ${MAKE} -f ${srctree}/Makefile INSTALL_MOD_PATH="${pdir}" INSTALL_MOD_STRIP=1 modules_install
scripts/package/buildtar:make ARCH="${ARCH}" -f ${srctree}/Makefile INSTALL_MOD_PATH="${tmpdir}" modules_install
scripts/package/kernel.spec:%{make} %{makeflags} INSTALL_MOD_PATH=%{buildroot} DEPMOD=true modules_install
tools/testing/ktest/ktest.pl:    run_command "$make INSTALL_MOD_STRIP=1 INSTALL_MOD_PATH=$tmpdir modules_install" or
```

One could workaround that like Archlinux is doing above, appending the /usr, but that is not very friendly.

So... it doesn't matter here that the host has a symlink to make /lib/modules and /usr/lib/modules the same thing. At least not if you are using those rules in the kernel build:  kernel will copy the files to a `$(INSTALL_MOD_PATH)/lib/modules/$(KERNELRELEASE)` and call depmod for it to created the indexes. However when depmod is built with --with-module-directory=/usr/lib/modules/, things won't work.

From what I can see in Masahiro's reply, even if this "normal" use case is fixed, the use case for cross-compiling could still break.  My proposal is:

a) Use `$(CROSS_COMPILE)pkg-config --variable=module_directory kmod` to get the **target** configuration, which should also work for the non-cross-compile case, since CROSS_COMPILE would't be set. Fallback to /lib/modules.
b) Set $MODLIB to take that into account
c) Add a -m to depmod which allows to set it in runtime, similarly to how we handle -b.

In this scenario, a distro using --with-module-directory should also support `depmod ... -m /usr/lib/modules`. I think that is reasonable and we can quickly add the new arg and backport to v33.

I think past patches from @hramrach do most of these, except (c).

**Comment by guillemj** [comment] 2024-08-28 11:00
> So... it doesn't matter here that the host has a symlink to make /lib/modules and /usr/lib/modules the same thing. At least not if you are using those rules in the kernel build: kernel will copy the files to a `$(INSTALL_MOD_PATH)/lib/modules/$(KERNELRELEASE)` and call depmod for it to created the indexes. However when depmod is built with --with-module-directory=/usr/lib/modules/, things won't work.

Hmm, assuming that the host filesystem layout will match the system we are building for always seems sketchy though. For Linux, this has always been somewhat hardcoded, but that also seems unnecessarily limiting TBH. :) But then you can configure the runtime modules path during a kernel build to set an alternative.

Thanks in any case for the Linux discussion pointers, I've got a local patch queued for submission for the kernel adding `/usr/lib/modules` to the list of runtime paths to look for modules from Linux, which I was planning to send upstream, but I'll have a peek at these pointers before doing so.

My main motivation for these changes is that the location on the  packaging (.deb) and physically on disk for these pathnames is under `/usr` and having to go through the symlinks in `/` is less robust (as symlinks are easier to modify or disappear than a directory), can give bad or no results on queries, and directory aliasing can in general be problematic. In addition I'd like to reach a point where some of these symlinks (the ones that are not involved in defined ABIs such as `/bin` for the shell, or `/lib64` for the dynamic linker on amd64 for example) could in the (far) future (once there are no more call sites or users of the old pathnames) be candidates for removal (for example I can see `/sbin` or `/lib`  being removable on amd64 where the dynamic linker lives under `/lib64`). So I'm trying to go over most of Debian to fix or improve this situation. And in any case I think using the canonical pathnames (or not using absolute pathnames and using PATH-like mechanisms for lookups) out of correctness is the way forward.

> From what I can see in Masahiro's reply, even if this "normal" use case is fixed, the use case for cross-compiling could still break. My proposal is:
> 
> a) Use `$(CROSS_COMPILE)pkg-config --variable=module_directory kmod` to get the **target** configuration, which should also work for the non-cross-compile case, since CROSS_COMPILE would't be set. Fallback to /lib/modules. b) Set $MODLIB to take that into account c) Add a -m to depmod which allows to set it in runtime, similarly to how we handle -b.
> 
> In this scenario, a distro using --with-module-directory should also support `depmod ... -m /usr/lib/modules`. I think that is reasonable and we can quickly add the new arg and backport to v33.
> 
> I think past patches from @hramrach do most of these, except (c).

Ah, these three points look like the correct way forward, indeed! I think having all that supported in kmod would really help. Thanks!

**Comment by guillemj** [comment] 2024-08-28 11:16
> Thanks in any case for the Linux discussion pointers, I've got a local patch queued for submission for the kernel adding `/usr/lib/modules` to the list of runtime paths to look for modules from Linux, which I was planning to send upstream, but I'll have a peek at these pointers before doing so.

Ah sorry, correction, the patch I've got locally is for `/usr/lib/firmware`!

**Comment by guillemj** [comment] 2024-08-28 12:26
> But then you can configure the runtime modules path during a kernel build to set an alternative.

Uff, was also thinking about the firmware path here, sorry, too many context switches. :)

**Closed** 2024-09-10 18:31 UTC
Labels: bug
